apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
  namespace: webserver2
  labels:
    app: webserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
              ISTIO_META_DNS_CAPTURE: "true"
              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    spec:
      containers:
        - name: webserver2
          image: 192.16.0.20:5000/service-a:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://192.16.0.20:4318
            - name: DB_HOST
              value: 192.16.0.20
            - name: DB_USER
              value: gm_user
            - name: DB_PASS
              value: ~bPjUAY|aP,"ps_2
            - name: DB_NAME
              value: homelab
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
