apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
spec:
  template:
    spec:
      containers:
        - name: webserver2
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
