apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: prometheus # Ajusta según el labelSelector de tu Prometheus Operator
spec:
  selector:
    matchLabels:
      app: istiod # Ajusta si el Service tiene otro label
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring # Verifica que el Service tenga ese port name
      interval: 30s
      path: /metrics
