apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - istio-telemetry.yaml
  #- istio-destination-rule.yaml
  #- istio-vs.yaml
