apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox
  namespace: argocd
  labels:
    scope: monitoring
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-change.slack: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  destination:
    namespace: monitoring
    server:
      # prettier-ignore
      {{ .Values.destinationServer | default .Values.spec.destination.server }}
  source:
    # prettier-ignore
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.2.0
    helm:
      values: |
        fullnameOverride: blackbox-exporter
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2"]
                method: GET
                preferred_ip_protocol: "ip4"
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
