apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  destination:
    namespace: monitoring
    server:
      # prettier-ignore
      {{ .Values.destinationServer | default .Values.spec.destination.server }}
  source:
    # prettier-ignore
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.1
    helm:
      releaseName: prometheus
      values: |
        prometheus:
          prometheusSpec:
            remoteWrite:
              - url: http://192.16.0.20:20291/api/v1/receive
                headers:
                  THANOS-TENANT: mycluster-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
