apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  labels:
    scope: monitoring
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator.git
    path: example/prometheus-operator-crd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
